Repository edgexfoundry/device-gpio, pull requests merged in 2022-04, with the labels that each got.

#21 feat: enable gosec and default linter set
  .golangci.yml
  Makefile
  internal/driver/drv_sysfs.go
Labels: kamakura

#23 feat: enable security hardening
  Makefile
Labels: kamakura

#24 fix: remove set of direction of a get GPIO or read
  README.md
  cmd/res/devices/device.led.gpio.toml
  cmd/res/profiles/device.led.gpio.yaml
  internal/driver/driver.go
Labels: bug, kamakura

#26 docs: Add CHANGELOG.md
  CHANGELOG.md
Labels: documentation
